cameras:
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.162/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-peeples-cam-3"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.228/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-central-cam-2"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.155/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-douglas-cam-2"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.222/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-peeples-cam-1"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.247/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-magnolia-cam-2"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.166/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-georgia-cam-1"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.218/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-lindsay-cam-2"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.224/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-houston-cam-1"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.242/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-douglas-cam-1"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.165/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-georgia-cam-3"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.159/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-houston-cam-2"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.248/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-magnolia-cam-1"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.216/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-georgia-cam-2"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.223/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-peeples-cam-2"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.229/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-central-cam-1"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.219/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-lindsay-cam-1"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.225/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-houston-cam-3"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.246/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-magnolia-cam-3"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.147/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-lindsay-cam-3"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.170/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-central-cam-3"
  - url: "http://consumer:IyKv4uY7%g^8@10.199.51.171/axis-cgi/mjpg/video.cgi?resolution=1920x1080"
    camera_id: "mlk-douglas-cam-3"


kafka:
  - bootstrap-servers: "sckafka1.simcenter.utc.edu"
    topic: "cuip_vision_events"